CREATE TABLE users (
  id SERIAL,
  name VARCHAR(80) NOT NULL,
  login VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(200) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modified_at TIMESTAMP NOT NULL,
  deleted BOOL NOT NULL DEFAULT FALSE,
  las_login TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(id)
)